[package]
name = "genshin-wish-montecarlo"
version = "0.1.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
clap = { version = "~4.0", features = [ "cargo" ] }
fastrand = "~1.8"
